### ISSUE TITLE
Why banned from dbl.oisd.nl/

### ISSUE THREAD

**Issue by Siewert308SW** [ookangzheng/dbl-oisd-nl#1]
Just noticed my PiHole had a error while updating gravity.
Saw https://dbl.oisd.nl/ didn't respond.
When i try to reach to https://dbl.oisd.nl/ i get a permission error.
When i go to the same url by my mobile data plan and there for a other ip i can reach it.
My IP is **.*66.21.119

**Comment by ookangzheng** [comment]
Sorry, I can't help here, please reach out to the author.

**Comment by pietervw** [comment]
Please add a screenshot of the permission error. 

On 11 March 2019 10:36:45 pm GMT+02:00, Siewert Lameijer <notifications@github.com> wrote:
>Just noticed my PiHole had a error while updating gravity.
>Saw https://dbl.oisd.nl/ didn't respond.
>When i try to reach to https://dbl.oisd.nl/ i get a permission error.
>When i go to the same url by my mobile data plan and there for a other
>ip i can reach it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ookangzheng/dbl-oisd-nl/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ookangzheng** [comment]
I think the problem is you got the maximum hits per day. 
If your IP download 1 time before, before next update you aren't able to download again. Have to wait for maybe 12 hours ( I guess ~~ )

**Comment by Siewert308SW** [comment]
@pietervw 
Sorry for the late reply, but no screenshot available as it's a 404 error.

@ookangzheng 
Could be the reason cause it's working again.
Still wonder has it updates 2times a week.

**Comment by ookangzheng** [comment]
@Siewert308SW I think would be good just update your pi-hole list every 24 hours, then that will be no problem. As far as I know, dbl.oisd.nl will reset all cache on everytime update
