### ISSUE TITLE
Many lists empty

### ISSUE THREAD

**Issue by ultrawyde** [ookangzheng/dbl-oisd-nl#13]
After today's update, many files are empty.

**Comment by thomasmerz** [comment]
Maybe due to this announcement on https://oisd.nl/downloads ?

TL;DR:

>    To simplify things;
>
>    oisd will continue only in abp-style (Adblock(Plus)-style domains) with the following 3 lists;
>
>    [big.oisd.nl](https://big.oisd.nl/)
    (The go-to oisd list)
    [small.oisd.nl](https://small.oisd.nl/)
    (if the big one is too big)
    [nsfw.oisd.nl](https://nsfw.oisd.nl/)
    (blocks shock/porn/adult)

**Comment by durablenapkin** [comment]
Some good news - the author reverted the change to just 3 blocklists and is again offering all previously offered syntaxes: https://oisd.nl/

> The Change to one syntax was reverted.

**Comment by thomasmerz** [comment]
@ultrawyde or @ookangzheng , please close this issue because it's not an issue anymore 👍🏼
