### ISSUE TITLE
Why block secure.livechatinc.com?

### ISSUE THREAD

**Issue by MinhThienDX** [ookangzheng/dbl-oisd-nl#2]
When I go to https://www.easeus.com/ and use **Live Chat** => **Pre-Sales Inquiry** function (top right of the page).
It open a popup but that popup's content is replaced by 1x1 GIF.
I check pfBlockerNG log and I found this:
`
DNSBL-HTTPS,Mar 18 09:14:05,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,+
DNSBL-HTTPS,Mar 18 09:14:09,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:09,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-1x1,Mar 18 09:14:09,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:09,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:10,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-1x1,Mar 18 09:14:10,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:10,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:14,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,+
DNSBL-1x1,Mar 18 09:14:14,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:14,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:15,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-1x1,Mar 18 09:14:15,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
DNSBL-HTTPS,Mar 18 09:14:15,secure.livechatinc.com,*.30,Unknown,DNSBL,DNSBL_dbl_oisd_nl,secure.livechatinc.com,dbl_oisd_nl_pi_hole,-
`
With *.30 is my local IP
I am curious about the block reason, can you tell me about it?

**Comment by ookangzheng** [comment]
Im not the author, go here and report https://www.reddit.com/comments/dwxgld
