### ISSUE TITLE
Blocking prod3-api.acompli.net breaks the mobile Outlook app

### ISSUE THREAD

**Issue by crssi** [ookangzheng/dbl-oisd-nl#3]
Blocking `acompli.net`, that is more specific `prod3-api.acompli.net` breaks the functionality of mobile [Outlook](https://www.microsoft.com/en-us/microsoft-365/outlook-mobile-for-android-and-ios) app, where constantly reports `Internet connection error` messages.

Whitelisting `prod3-api.acompli.net` resolves the issue.

Cheers and thank you for your list

**Comment by rblaine95** [comment]
This repository is a mirror of `https://dbl.oisd.nl`
If you have any problems raise it with the maintainer of the list - `sjhgvr`

```
#  Info/Issues | https://redd.it/dwxgld
```

**Comment by ookangzheng** [comment]
will close this issue 🍺
