### ISSUE TITLE
not updated

### ISSUE THREAD

**Issue by Macqael** [ookangzheng/dbl-oisd-nl#6]
it seem the bot don't update these mirror anymore

**Comment by ookangzheng** [comment]
I will try to contact the owner. Will temporary update this mirror every day.

**Comment by michaelb-ae** [comment]
thanks it seems (in my try to reproduce, script cannot download the list anymore i don't know why through in my case i have tried with python url lib

**Comment by ookangzheng** [comment]
I use nodejs and curl
