### ISSUE TITLE
Add extra and nsfw list

### ISSUE THREAD

**Issue by BirdInFire** [ookangzheng/dbl-oisd-nl#9]
Can you add these list to this ?

https://oisd.nl/downloadsXtra

Who show their "nsfw" list and "extra" list

**Comment by ookangzheng** [comment]
Will try during free time

**Comment by BirdInFire** [comment]
Take your time, it's an idea to follow their new list ;)

**Comment by ookangzheng** [comment]
@BirdInFire I update the list, pls try it out.

**Comment by BirdInFire** [comment]
@ookangzheng i conforme after many day it work flawlessly thanks again
